FROM ubuntu:focal
LABEL maintainer="Maximus Developers <dev@maximuschain.com>"
LABEL description="Dockerised MaximusCore"

ARG USER_ID
ARG GROUP_ID
ARG TAG
ARG GITHUB_REPOSITORY

ENV HOME /home/maximus

# add user with specified (or default) user/group ids
ENV USER_ID ${USER_ID:-1000}
ENV GROUP_ID ${GROUP_ID:-1000}
RUN groupadd -g ${GROUP_ID} maximus && \
    useradd -u ${USER_ID} -g maximus -s /bin/bash -m -d /home/maximus maximus  && \
    mkdir /home/maximus/.maximuscore && \
    chown ${USER_ID}:${GROUP_ID} -R /home/maximus

RUN apt-get update && \
    apt-get -y install --no-install-recommends \
    wget \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN echo "https://github.com/${GITHUB_REPOSITORY}/releases/download/v${TAG}/maximuscore-${TAG}-$arch.tar.gz"

RUN mach=$(uname -m) \
      && case $mach in aarch64) arch="aarch64-linux-gnu"; ;; x86_64) arch="x86_64-linux-gnu"; ;;  *) echo "ERROR: Machine type $mach not supported."; ;; esac \
      && wget https://github.com/${GITHUB_REPOSITORY}/releases/download/v${TAG}/maximuscore-${TAG}-$arch.tar.gz -P /tmp \
      && tar -xvf /tmp/maximuscore-*.tar.gz -C /tmp/ \
      && find /tmp/maximuscore*/bin -type f ! -name 'maximus-qt' -exec cp {} /usr/local/bin \; \
      && rm -rf /tmp/maximuscore* \
      && chmod a+x /usr/local/bin/*

USER maximus

VOLUME ["/home/maximus"]

COPY docker-entrypoint.sh /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]

EXPOSE 9938 9939 19938 19939

WORKDIR /home/maximus
